[build]
  publish = "."
  functions = "netlify/functions"
  command = "chmod +x build.sh && ./build.sh"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/draft-state.json"
  to = "/.netlify/functions/draft-state"
  status = 200

[[redirects]]
  from = "/api/draft-state"
  to = "/.netlify/functions/draft-state"
  status = 200

[[redirects]]
  from = "/api/update-draft-state"
  to = "/.netlify/functions/update-draft-state"
  status = 200

[[redirects]]
  from = "/api/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/api/init-db"
  to = "/.netlify/functions/init-db"
  status = 200

[[redirects]]
  from = "/api/db-test"
  to = "/.netlify/functions/db-test"
  status = 200

[[redirects]]
  from = "/api/hello"
  to = "/.netlify/functions/hello"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Cache-Control = "no-cache, no-store, must-revalidate"
